print("This is the first line of printing")
print("This is the second line of printing")
print("This is the third line of printing")
print("This is the fourth line of printing")
print("This is the fifth line of printing")